import {
  useRxRequest,
  useRxRequests,
  BaseRxObservableConfig,
  MultiRxObservableConfig,
  SingleRxObservableStateListener,
  MultiRxObservableStateListener,
  SingleRxObservableConfig,
  RxRequestConfig,
  RxRequestResult,
  OnErrorUseRxRequests,
  OnSuccessUseRxRequests,
  OnSuccessUseRxRequest,
  OnErrorUseRxRequest,
  UseRxRequestsValue,
  UseRxRequestFetchFn,
  UseRxRequestValue,
  MultiRxObservableConfigure,
  SingleRxObservableConfigure,
  SingleRxObservableState,
  MultiRxObservableState,
} from "./dist";

export type {
  BaseRxObservableConfig,
  MultiRxObservableConfig,
  SingleRxObservableStateListener,
  MultiRxObservableStateListener,
  SingleRxObservableConfig,
  RxRequestConfig,
  RxRequestResult,
  OnErrorUseRxRequests,
  OnSuccessUseRxRequests,
  OnSuccessUseRxRequest,
  OnErrorUseRxRequest,
  UseRxRequestsValue,
  UseRxRequestFetchFn,
  UseRxRequestValue,
  MultiRxObservableConfigure,
  SingleRxObservableConfigure,
  SingleRxObservableState,
  MultiRxObservableState,
};

export { useRxRequests, useRxRequest };
